language: java
env:
  - PLAY_VERSION=1.2.5
before_script:
  - wget http://downloads.typesafe.com/releases/play-${PLAY_VERSION}.zip
  - unzip -q play-${PLAY_VERSION}.zip
script: play-${PLAY_VERSION}/play deps --sync        